# Generated by Django 3.1.3 on 2020-11-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTittle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=10000)),
            ],
        ),
    ]
