# Generated by Django 3.0.5 on 2021-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTittle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=10000)),
            ],
        ),
    ]
