# Generated by Django 3.0.5 on 2021-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTittle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=10000)),
            ],
        ),
    ]
